/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package taximetro;


import es.javiergarbedo.coordinateslib.CoordinatesConverter;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import org.apache.commons.lang3.time.DurationFormatUtils;
import org.apache.commons.validator.routines.CreditCardValidator;



/**
 *
 * @author Usuario
 */
public class Taximetro extends javax.swing.JFrame {
    //Declaraciones 
    final double TARIFAXMINUTO = 0.50; //TarifaMinutos
    final double IVA = 0.21;  //Iva
    int contador = 0; //Contador para el número de tickets
    //Declaraciones para la clase Calendar para la hora y fecha
    Calendar ahora; //fecha con clase calendar
    Calendar fechaHoraSalida; 
    Calendar fechaHoraFin;
    DateFormat formatoHora = DateFormat.getTimeInstance(DateFormat.MEDIUM);
    DateFormat formatoFecha = DateFormat.getTimeInstance(DateFormat.MEDIUM);
    /**
     * Creates new form Taximetro
     */
    public Taximetro() {
        initComponents();
        //Inicialmente tendremos el botón rojo apagado
        jToggleButtonRojo.setEnabled(false); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldLatitud = new javax.swing.JTextField();
        jTextFieldLongitud = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelTextoLatitud = new javax.swing.JLabel();
        jLabelLongitud = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelImagenTaxi = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldDestino = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jToggleButtonVerde = new javax.swing.JToggleButton();
        jToggleButtonRojo = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldTextoCredito = new javax.swing.JTextField();
        jButtonComprobar = new javax.swing.JButton();
        jLabelMapaRuta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Latitud");

        jLabel3.setText("Longitud");

        jTextFieldLongitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLongitudActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldLatitud, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTextoLatitud)
                                    .addComponent(jLabelLongitud))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldLatitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabelTextoLatitud))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabelLongitud))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel1.setText("Posición GPS Inicio");

        jLabelImagenTaxi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/taxi.png")));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setText("Destino");

        jTextFieldDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDestinoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldDestino)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setText("Datos del trayecto");

        jToggleButtonVerde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/green.png")));
        jToggleButtonVerde.setText("VERDE");
        jToggleButtonVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonVerdeActionPerformed(evt);
            }
        });

        jToggleButtonRojo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/stop.png")));
        jToggleButtonRojo.setText("ROJO");
        jToggleButtonRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonRojoActionPerformed(evt);
            }
        });

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jScrollPane1.setViewportView(jTextArea);

        jLabel9.setText("Tarjeta de credito");

        jTextFieldTextoCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTextoCreditoActionPerformed(evt);
            }
        });

        jButtonComprobar.setText("Comprobar");
        jButtonComprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComprobarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabelImagenTaxi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMapaRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButtonVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButtonRojo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonComprobar)
                        .addGap(0, 17, Short.MAX_VALUE))
                    .addComponent(jTextFieldTextoCredito)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelImagenTaxi, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jLabel7)
                .addGap(3, 3, 3)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonComprobar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTextoCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleButtonVerde, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                            .addComponent(jToggleButtonRojo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelMapaRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldLongitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLongitudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLongitudActionPerformed

    private void jTextFieldDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDestinoActionPerformed

    private void jToggleButtonVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonVerdeActionPerformed
        //Todo al activar el botón bandera verde
        
        //Se enciende el botón rojo,para parar el trayecto
        jToggleButtonRojo.setEnabled(true);
        
        //Al pulsar el boton verde acabamos de recoger la hora en la que salimos
        fechaHoraSalida = Calendar.getInstance();
        formatoHora.format(fechaHoraSalida.getTime());
        
        //Declaraciones para latitud y longitud,nos dan lo escrito en ambos
        double latitud = Double.valueOf(jTextFieldLatitud.getText());
        double longitud = Double.valueOf(jTextFieldLongitud.getText());
        //Se transforma en los labels las coordenadas,gracias a la clase
        CoordinatesConverter conversorCoordenadas = new CoordinatesConverter();
        jLabelTextoLatitud.setText(CoordinatesConverter.decimalToDMS(latitud));
        jLabelLongitud.setText(CoordinatesConverter.decimalToDMS(longitud));
        
        //Cambia los siguientes valores por las direciones de origen y destino deseadas
        String origen = jTextFieldLatitud.getText() + "," + jTextFieldLongitud.getText();
        String destino = jTextFieldDestino.getText();
        //Hay que sustituir los espacios por el carácter %20 para que se
        //  interprete bien la URL que se generará
        destino = destino.replaceAll(" ", "%20");
        //Cambia el nombre [etiqueta] por el nombre de un objeto JLabel (etiqueta) que
        //  has debido colocar antes en el formulario y que será donde se muestre el mapa.
        //  Deja la etiqueta del formulario sin ningún texto en el diseño.
        javax.swing.JLabel jLabelMapa = jLabelMapaRuta;
        //Indica aquí el tamaño que desees para el mapa
        int tamHorizontal =200;
        int tamVertical = 270;
        //Puedes encontrar más información sobre el uso de mapas estáticos de Google Maps aquí:
        //  http://code.google.com/intl/es-ES/apis/maps/documentation/staticmaps/

        //A partir de aquí no hace falta cambiar nada
        try {
            String txtDireccionImagenMapa = "http://maps.google.com/maps/api/staticmap?path="+
                    origen+"|"+destino+"&size="+tamHorizontal+"x"+tamVertical+
                    "&language=ES&sensor=false";
            System.out.println(txtDireccionImagenMapa);
            java.awt.Toolkit toolkit = java.awt.Toolkit.getDefaultToolkit();
            java.awt.Image imagenMapa = toolkit.getImage(new java.net.URL(txtDireccionImagenMapa)); 
            jLabelMapa.setIcon(new javax.swing.ImageIcon(imagenMapa));    
        } catch(java.net.MalformedURLException e) {   
            javax.swing.JOptionPane.showMessageDialog(this, "La dirección de imagen indicada no es correcta");
        }
        jToggleButtonVerde.setEnabled(false);
    }//GEN-LAST:event_jToggleButtonVerdeActionPerformed

    private void jTextFieldTextoCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTextoCreditoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTextoCreditoActionPerformed

    private void jToggleButtonRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonRojoActionPerformed
        //Todo al pulsar el botón rojo
        
        //Botón verde para nuevo trayecto
        jToggleButtonVerde.setEnabled(true);
        //El número de tickets,partiendo desde 0
        DecimalFormat formatoTicket = new DecimalFormat("0000");
        contador++;
        String formatoContador = formatoTicket.format(contador);
        
        //Calculo de la hora actual
        fechaHoraFin = Calendar.getInstance(); //Obtenemos la hora final trayecto
        long milisegundosSalida = fechaHoraSalida.getTimeInMillis(); //Variable Hora salida(La tomamos en milisegundos)
        long milisegundosFin = fechaHoraFin.getTimeInMillis(); //Variable Hora llegada(la tomamos en milisegundos)
        long duracionTrayectoMilis = milisegundosFin - milisegundosSalida;   //Restamos para saber la diferencia del tiempo
        String formatoMilis = DurationFormatUtils.formatDuration(duracionTrayectoMilis,"HH:mm:ss"); //Resultaod final convertido a hora,minutos y segundos
        
        //Calculos del precio
        NumberFormat formatoMoneda = NumberFormat.getCurrencyInstance();
        double TrayectoduracionSegundos = (duracionTrayectoMilis / 1000);
        double importe = (TrayectoduracionSegundos / 60) * TARIFAXMINUTO;
        //Calculo del importe con el IVA
        double importeIva = importe * IVA; 
        double importeTotal = importe + importeIva; 

        //Escribe en el area de Texto nº del ticket
        jTextArea.setText("TICKET\n");
        jTextArea.append("Nºticket: " + formatoContador);
        jTextArea.append("\n\n");
        //Datos de interes del ticket
        jTextArea.append("Hora bajada de bandera: " + formatoHora.format(fechaHoraSalida.getTime()));
        jTextArea.append("\nHora fin de trayecto: " + formatoHora.format(fechaHoraFin.getTime()));
        jTextArea.append("\nDuración de trayecto: " + formatoMilis);
        jTextArea.append("\nTarifa por minuto: " + formatoMoneda.format(TARIFAXMINUTO));
        jTextArea.append("\n\n");
        jTextArea.append("Importe: " + formatoMoneda.format(importe));
        jTextArea.append("\nIVA: " + formatoMoneda.format(importeIva));
        jTextArea.append("\nImporte total: " + formatoMoneda.format(importeTotal));
        jTextArea.append("\n\n");
        //Fecha y agradecimiento
        ahora = Calendar.getInstance();                        		
        String fechaTexto = String.valueOf(ahora.get(Calendar.DAY_OF_MONTH));
        fechaTexto += "/" + (String.valueOf((ahora.get(Calendar.MONTH))+1));
        fechaTexto += "/" + (String.valueOf(ahora.get(Calendar.YEAR)));
        String horaTexto = String.valueOf(ahora.get(Calendar.HOUR_OF_DAY));
        horaTexto += ":" + (String.valueOf(ahora.get(Calendar.MINUTE)));
        horaTexto += ":" + (String.valueOf(ahora.get(Calendar.SECOND)));
        jTextArea.append("\nFecha:"+ fechaTexto);
        jTextArea.append("\n¡Gracias!");
                
        jToggleButtonRojo.setEnabled(false);
    }//GEN-LAST:event_jToggleButtonRojoActionPerformed

    private void jButtonComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComprobarActionPerformed
       //Comprobacion de la tarjeta de credito
        //Nos ayudamos de la clase y declaramos el boolean
        CreditCardValidator validadorTarjeta = new CreditCardValidator();
        boolean validacionTarjeta = validadorTarjeta.isValid(jTextFieldTextoCredito.getText());
        String estadoTarjeta = (validacionTarjeta==true) ? "La Tarjeta es Valida" : "La Tarjeta no es Valida";
        JOptionPane.showMessageDialog(this,estadoTarjeta,"Atención",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonComprobarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Taximetro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Taximetro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonComprobar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelImagenTaxi;
    private javax.swing.JLabel jLabelLongitud;
    private javax.swing.JLabel jLabelMapaRuta;
    private javax.swing.JLabel jLabelTextoLatitud;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JTextField jTextFieldDestino;
    private javax.swing.JTextField jTextFieldLatitud;
    private javax.swing.JTextField jTextFieldLongitud;
    private javax.swing.JTextField jTextFieldTextoCredito;
    private javax.swing.JToggleButton jToggleButtonRojo;
    private javax.swing.JToggleButton jToggleButtonVerde;
    // End of variables declaration//GEN-END:variables
}
